### ISSUE TITLE
Error: Location could not routed to or from.

### ISSUE THREAD

**Issue by alecava58** [itinero/optimization#2]
Ben, I'm trying TSP and I have this case:

With this set of coordinates if I try to calculate route everything is ok but when I try TSP 2 of these routes give the "Location could not routed to or from".
If you inspect the result you can see result.WeightMatrix.Errors = 2.

            var lat = new double[] { 45.516299000000, 45.342569300000, 45.420742000000, 45.506180600000, 45.506180600000 };
            var lon = new double[] { 9.011622100000, 9.275663400000, 9.112615900000, 8.986078000000, 8.986078000000 };

            IList<Coordinate> coo = new List<Coordinate>();
            for (var i = 0; i < lat.Length; i++)
                coo.Add(new Coordinate((float)lat[i], (float)lon[i]));
            TSPRouter routerTSP = new TSPRouter(new WeightMatrixAlgorithm(router, profile, coo.ToArray())); //, 0, coo.Count - 1);
            routerTSP.Run();
            Console.WriteLine(string.Format("End OptimizeTSP: has succeeded = {0}", routerTSP.HasSucceeded));

**Comment by xivk** [comment]
This is the same issue as before, the resolver is just the basic one, not the one with the connectivity checks, I'll see if I can improve this... or at least offer the option to inject another resolver.

**Comment by xivk** [comment]
There is already the option to inject a custom resolver by implementing:

https://github.com/itinero/routing/blob/develop/src/Itinero/Algorithms/Search/IMassResolvingAlgorithm.cs

The default implementation is this:

https://github.com/itinero/routing/blob/develop/src/Itinero/Algorithms/Search/MassResolvingAlgorithm.cs

I seem to have thought about this before... 👍 

The match edge function (https://github.com/itinero/routing/blob/develop/src/Itinero/Algorithms/Search/MassResolvingAlgorithm.cs#L42) can be replace by the one used here:

https://github.com/itinero/routing/blob/develop/src/Itinero/RouterBaseExtensions.cs#L642

I don't have time to do this now, consider it on my list because this would make a lot for sense!

**Comment by alecava58** [comment]
Ben, have you planned to release a not prerelease version of this library as is?

**Comment by xivk** [comment]
I need to write release notes and such but I have scheduled some time tomorrow to do this and to create a 1.1 release.

**Comment by xivk** [comment]
Ah ouwch, I assumed this issue was in the main Itinero 'routing' repo, **not** a release planned for this one just yet. I'll see if it's possible.

**Comment by alecava58** [comment]
Until this package is marked as prerelease I must mark my nuget package prerelease too.
It was just for this.

**Comment by xivk** [comment]
So I had a look and this is feature complete so I can do a release, will make one soon.

**Comment by alecava58** [comment]
Ok, for the moment I solved this issue following your suggestion above.

**Comment by xivk** [comment]
All ready for a release but I found an issue while testing with the latest Itinero, fixing that first and then I will create a release, should be something for tomorrow.

**Comment by alecava58** [comment]
Ok. Thanks to all.

-- Alessandro

Il 27 giu 2017 19:02, "Ben Abelshausen" <notifications@github.com> ha
scritto:

**Comment by xivk** [comment]
@alecava58 There is a stable package now... with a stable Itinero 1.1.1.

**Comment by alecava58** [comment]
Sorry Ben but I don't understand. I still see Itinero.Optimization 0.13.0-beta. 
Do you mean that optimization is inside Itinero 1.1.1. package?

**Comment by xivk** [comment]
Sorry, the nuget package didn't get published, it should be coming up now...

**Comment by alecava58** [comment]
Ok. Thanks.
