### ISSUE TITLE
Routing With Time WIndows

### ISSUE THREAD

**Issue by goisve** [itinero/optimization#33]
Hi, 
I'm experimenting with Time Windows.
I have a route  that i want it to start at 8:00 am  , with 80 stops without time windows and one  with time window 12:00 -14:00.
I tried setting the time window to  min =28800 (08:00) , max =61200 (17:00) to all stops except the one that I set it to min =43200 (12:00) , max = 50400 (14:00), but i seems like the time window is not working. 
Any suggestions how to set the correct time windows for this route?

**Comment by xivk** [comment]
This should be fixed now in https://github.com/itinero/optimization/commit/e0ea72a7c63159ba897e8469d1d3160e1575f157 and https://github.com/itinero/optimization/commit/06f3757fe3fc00ec544e3ab897d22f635e264cc0
