### ISSUE TITLE
Perfomance problem

### ISSUE THREAD

**Issue by VitoHusky** [itinero/optimization#4]
im currently using itenero to calculate the TSP Route.

I loaded the osm file (3gb) of Germany, converted it to a routing file (1GB).
The calculation works, but it needs 3 minutes for 4 stops, i tried to check it with 18 stops but this took to long.

It is restricted to "Vehicle.Car"
Are there more Options / Methods to increase the speed (40 stops should take not longer than 5 minutes)

```
var routerDb = new RouterDb();
routerDb.AddContracted(Vehicle.Car.Fastest());

            using (var stream = new FileInfo(routingFile).OpenRead())
            {
                routerDb = RouterDb.Deserialize(stream);
            }


var router = new Router(routerDb);
var route = router.CalculateTSP(Vehicle.Car.Fastest(), addresses.Select(x => x.Coordinate).ToArray());
```

**Comment by xivk** [comment]
First thing I can think of is that you should contract after you deserialize the routerdb in the above sample, or you should contract and then save the routerdb. In any case, you need to make sure there is a contracted graph inside the routerdb.

There is a problem with performance on matrix calculations currently but it should lead to this kind of timings.

**Comment by xivk** [comment]
This will 99% sure be fixed by the new Itinero version and the first release of this project. Closing this now, feel free to file another issue if you still have problems.
