### ISSUE TITLE
TSP TW

### ISSUE THREAD

**Issue by DanielSCBO** [itinero/optimization#7]
Hello I am trying to calculate a route with the algorithm TSP TW, but I do not understand the Time Window.

But I do not understand the Time Window. 

I need to calculate the route with this data for example:

-> Departure: 41.2483368,-8.625592
-> Customer 1: 41.1915741, -8.627647 | 09h-> 18h
-> Customer 2: 41.1169434,-8.625565  | 09h-> 09h30h
-> Customer 3: 41.1220551,-8.603654  | 09h-> 18h
-> Customer 4: 41.122985, -8.605524   | 09h-> 18h

Client 2 should be the first but the program says that the first is the Customer 3, all time windows is 0 except Customer 2, time windows is 0 -> 1800.

Any help?

Thanks

**Comment by xivk** [comment]
Time windows are relative to departure time, it's possible customer 2 can be reached within 30min from departure.

**Comment by xivk** [comment]
Hmm, 30mins seems optimistic now:

http://geojson.io/#id=gist:anonymous/2cde97ed7db5ae5289cfce4e66417588&map=12/41.1610/-8.6181

The issue also is that there is no 'delivery' time, stops at each customer are 0 seconds, something to be improved in future versions.

**Comment by xivk** [comment]
@LaBoss Closing this issue, feel free to reopen if you have more remarks/questions.
